swagger: '2.0'
info:
  title: Tags Duplicated Names Test
  version: '1.0.0'
paths: {}
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: store
    description: YOU DO NOT SEE THIS
